name: Performance Audit

on:
  pull_request:
    branches: [main]
  schedule:
    # Run weekly performance audit on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        run: |
          npm run preview &
          sleep 5
          lhci autorun
          pkill -f "vite preview" || true

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: |
            .lighthouseci/
            lighthouse-report.html
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Try to read the lighthouse results
            try {
              const resultsDir = '.lighthouseci';
              if (fs.existsSync(resultsDir)) {
                const files = fs.readdirSync(resultsDir);
                const manifestFile = files.find(f => f.includes('manifest.json'));
                
                if (manifestFile) {
                  const manifest = JSON.parse(fs.readFileSync(path.join(resultsDir, manifestFile)));
                  const summary = manifest[0]?.summary;
                  
                  if (summary) {
                    const comment = `## 🚀 Performance Audit Results

            | Category | Score | Status |
            |----------|-------|--------|
            | Performance | ${Math.round(summary.performance * 100)}% | ${summary.performance >= 0.9 ? '✅' : summary.performance >= 0.7 ? '⚠️' : '❌'} |
            | Accessibility | ${Math.round(summary.accessibility * 100)}% | ${summary.accessibility >= 0.95 ? '✅' : '⚠️'} |
            | Best Practices | ${Math.round(summary['best-practices'] * 100)}% | ${summary['best-practices'] >= 0.9 ? '✅' : '⚠️'} |
            | SEO | ${Math.round(summary.seo * 100)}% | ${summary.seo >= 0.8 ? '✅' : '⚠️'} |

            ${summary.performance < 0.9 ? '⚠️ Performance score below target (90%)' : ''}
            ${summary.accessibility < 0.95 ? '⚠️ Accessibility score below target (95%)' : ''}

            View full report in the artifacts section.`;
                    
                    github.rest.issues.createComment({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: comment
                    });
                  }
                }
              }
            } catch (error) {
              console.log('Could not generate performance comment:', error.message);
            }

  performance-regression-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (PR)
        run: npm ci

      - name: Install dependencies (Base)
        run: cd base && npm ci

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Build and audit PR
        run: |
          npm run build
          npm run preview &
          sleep 5
          lighthouse http://localhost:4173 --output json --output-path pr-results.json --quiet --chrome-flags="--headless --no-sandbox"
          pkill -f "vite preview" || true

      - name: Build and audit base
        run: |
          cd base
          npm run build
          npm run preview &
          sleep 5
          lighthouse http://localhost:4173 --output json --output-path ../base-results.json --quiet --chrome-flags="--headless --no-sandbox"
          pkill -f "vite preview" || true

      - name: Compare performance
        run: |
          node -e "
          const fs = require('fs');
          const prData = JSON.parse(fs.readFileSync('pr-results.json'));
          const baseData = JSON.parse(fs.readFileSync('base-results.json'));

          const prPerf = Math.round(prData.categories.performance.score * 100);
          const basePerf = Math.round(baseData.categories.performance.score * 100);
          const diff = prPerf - basePerf;

          console.log('Performance Comparison:');
          console.log('Base:', basePerf + '%');
          console.log('PR:', prPerf + '%');
          console.log('Difference:', (diff > 0 ? '+' : '') + diff + '%');

          if (diff < -5) {
            console.log('❌ Significant performance regression detected');
            process.exit(1);
          } else if (diff < 0) {
            console.log('⚠️ Minor performance regression');
          } else {
            console.log('✅ No performance regression');
          }
          "
